name: Java CI with Gradle and Deploy to EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Add EC2 to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy and Run on EC2
        run: |
          ssh -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
          
            rm -rf /home/ubuntu/app
          
            git clone https://github.com/dh2906/TravelPlanner.git /home/ubuntu/app
            cd /home/ubuntu/app
          
            chmod +x ./gradlew
            ./gradlew clean build -x test
          
            pkill -f app.jar || true
            nohup java -jar build/libs/*.jar --spring.config.location=file:/home/ubuntu/config/application.yml > /home/ubuntu/app/app.log 2>&1 &
          
          EOF